apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pos-deployment #BLUE tag 1.0.1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pos-deployment
  minReplicas: 25
  maxReplicas: 30
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 #if reached 2200m
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50 #if reached 2.2GB
